### ISSUE TITLE
How to set up a Zigbee 3.0 device to periodically report data to the hub and have the hub associate the data with the capability？

### ISSUE THREAD

**Issue by script0803** [SmartThingsCommunity/SmartThingsEdgeDrivers#1963]
I am working on an Edge driver for a Zigbee 3.0 meter. Since it is a three-phase device and can monitor both the forward energy and produced energy, my profile is written like this:

```yaml
name: "power-meter-bt"
components:
  - id: TotalForwardEnergy
    capabilities:
      - id: energyMeter
        version: 1
  - id: TotalReverseEnergy
    capabilities:
      - id: energyMeter
        version: 1
  - id: PhaseA
    capabilities:
      - id: powerMeter
        version: 1
      - id: currentMeasurement
        version: 1
      - id: voltageMeasurement
        version: 1
    categories:
      - name: CurbPowerMeter
  - id: PhaseB
    capabilities:
      - id: powerMeter
        version: 1
      - id: currentMeasurement
        version: 1
      - id: voltageMeasurement
        version: 1
    categories:
      - name: CurbPowerMeter
```

In the `init.lua` file, I initialize the device by binding the endpoint:

```lua
local function do_configure(driver, device)
  device:configure()
  device:send(device_management.build_bind_request(device, clusters.SimpleMetering.ID, driver.environment_info.hub_zigbee_eui, 10))
  device:send(device_management.build_bind_request(device, clusters.ElectricalMeasurement.ID, driver.environment_info.hub_zigbee_eui, 10))
  for _, attribute in ipairs(POWERMETER_CONFIGURATION_V2) do
    device:add_configured_attribute(attribute)
    device:add_monitored_attribute(attribute)
  end
  device:refresh()
  
end

local device_init = function(self, device)
  device:set_field(constants.SIMPLE_METERING_MULTIPLIER_KEY, 1, {persist = true})
  device:set_field(constants.SIMPLE_METERING_DIVISOR_KEY, 100, {persist = true})
  device:set_field(constants.ELECTRICAL_MEASUREMENT_MULTIPLIER_KEY, 1, {persist = true}) -- ACPower
  device:set_field(constants.ELECTRICAL_MEASUREMENT_DIVISOR_KEY, 1, {persist = true}) -- ACPower
  device:set_field("RMSVOLTAGE_MULTIPLIER", 1, {persist = true})
  device:set_field("RMSVOLTAGE_DIVISOR", 100, {persist = true})
  device:set_field("RMSCURRENT_MULTIPLIER", 1, {persist = true})
  device:set_field("RMSCURRENT_DIVISOR", 100, {persist = true})
  
end
```

I set the handler for each attribute and update the corresponding capability with the received values:

```lua
local function energy_handler(driver, device, value, zb_rx)
  local multiplier = device:get_field(constants.SIMPLE_METERING_MULTIPLIER_KEY) or 1
  local divisor = device:get_field(constants.SIMPLE_METERING_DIVISOR_KEY) or 100
  local raw_value = value.value * multiplier/divisor
  
  device:emit_component_event(device.profile.components["TotalForwardEnergy"], capabilities.energyMeter.energy({value = raw_value, unit = "kWh" }))
end

local function power_phaseA_handler(driver, device, value, zb_rx)
  local multiplier = device:get_field(constants.ELECTRICAL_MEASUREMENT_MULTIPLIER_KEY) or 1
  local divisor = device:get_field(constants.ELECTRICAL_MEASUREMENT_DIVISOR_KEY) or 1
  local raw_value = value.value * multiplier/divisor -- Uint W
  device:emit_component_event(device.profile.components["PhaseA"], capabilities..powerMeter.power({value = raw_value, unit = "W"}))
end
```
```lua
lifecycle_handlers = {
    init = device_init,
    doConfigure = do_configure,
  },
  zigbee_handlers = {
    attr = {
      [clusters.SimpleMetering.ID] = {
        [clusters.SimpleMetering.attributes.CurrentSummationDelivered.ID] = energy_handler,
        [clusters.SimpleMetering.attributes.CurrentSummationReceived.ID] = produced_energy_handler
        },
      [clusters.ElectricalMeasurement.ID] = {
        [clusters.ElectricalMeasurement.attributes.ActivePower.ID] = power_phaseA_handler,
        [clusters.ElectricalMeasurement.attributes.ActivePowerPhB.ID] = power_phaseB_handler,
        [clusters.ElectricalMeasurement.attributes.ActivePowerPhC.ID] = power_phaseC_handler,
        [clusters.ElectricalMeasurement.attributes.RMSVoltage.ID] = voltage_phaseA_handler,
        [clusters.ElectricalMeasurement.attributes.RMSVoltagePhB.ID] = voltage_phaseB_handler,
        [clusters.ElectricalMeasurement.attributes.RMSVoltagePhC.ID] = voltage_phaseC_handler,
        [clusters.ElectricalMeasurement.attributes.RMSCurrent.ID] = current_phaseA_handler,
        [clusters.ElectricalMeasurement.attributes.RMSCurrentPhB.ID] = current_phaseB_handler,
        [clusters.ElectricalMeasurement.attributes.RMSCurrentPhC.ID] = current_phaseC_handler
      }
    }
  },
```
However, this Edge driver has an issue and is not functional.
