### ISSUE TITLE
conflicting capabilities

### ISSUE THREAD

**Issue by veonua** [SmartThingsCommunity/SmartThingsEdgeDrivers#267]
```
name: fail1
components:
- id: main
  capabilities:
  - id: temperatureMeasurement
    version: 1
  - id: thermostatHeatingSetpoint
    version: 1
  - id: thermostatCoolingSetpoint
    version: 1
  - id: thermostatMode
    version: 1
  - id: fanSpeed
    version: 1
  - id: thermostatOperatingState
    version: 1
  - id: fanOscillationMode
    version: 1
  
  
  categories:
  - name: Thermostat

- id: outdoor
  capabilities:
    - id: temperatureMeasurement
      version: 1
```

the device with this profile fails to render in iOS, 
conflicting row **fanOscillationMode**
