### ISSUE TITLE
Default device icon

### ISSUE THREAD

**Issue by sky-nie** [SmartThingsCommunity/SmartThingsEdgeDrivers#29]
Devices with categories "RemoteController" are showed with default icon in SmartThings APP.
Is this normal? It seems that this is not the case in the DTH.

**Comment by veonua** [comment]
Probably Edge/App teams need better coordination, for some reason without extra

```
metadata:
  deviceType: RemoteController
  ocfDeviceType: x.com.st.d.remotecontroller
  deviceTypeId: RemoteController  
```

the icon does not stay in the app.
