### ISSUE TITLE
Generic Z Wave thermostat without Fan mode (0x44)

### ISSUE THREAD

**Issue by teo78** [SmartThingsCommunity/SmartThingsEdgeDrivers#488]
Hi!

I have a few Z Wave thermostats (https://heatit.com/produkt/9437/heatit-z-temp2-white) that use a cloud Device Handler when added.
This is their fingerprint: ``zw:Fs2a type:0806 mfr:019B prod:0004 model:0204 ver:1.02 zwv:7.11 lib:03 cc:5E,55,98,9F,6C,22 sec:86,85,8E,59,72,5A,87,73,80,71,7A,40,43,42,75,70,31``

I looked at the fingerprint of the generic edge drivers (below) and it seems they require command class 0x44 (Fan mode) which this ones don't have.
Any chance you can update the generic drivers to support thermostats without command class 0x44? (as far as I can see that's the only thing preventing it to match).

```
zwaveGeneric:
  - id: "GenericBatteryThermostat"
    deviceLabel: Z-Wave Battery Thermostat
    commandClasses:
      supported:
        - 0x43
        - 0x40
        - 0x44
        - 0x31
        - 0x80
    deviceProfileName: base-thermostat
  - id: "GenericThermostat"
    deviceLabel: Z-Wave Thermostat
    commandClasses:
      supported:
        - 0x43
        - 0x40
        - 0x44
        - 0x31
    deviceProfileName: base-thermostat-without-battery
```

Thanks,
Anders
